---
fabric_name: SITE1_FABRIC

# Set Design Type to L3L2 with EVPN VXLAN
design:
  type: l3ls-evpn

# Spine Switches
spine:
  defaults:
    platform: cEOS
    loopback_ipv4_pool: 10.250.1.0/24
    bgp_as: 65100
  nodes:
    - name: DC1-spine1
      id: 1
      mgmt_ip: 192.168.0.31/24
    - name: DC1-spine2
      id: 2
      mgmt_ip: 192.168.0.32/24

# Leaf Switches
l3leaf:
  defaults:
    platform: cEOS 
    spanning_tree_priority: 4096 
    spanning_tree_mode: mstp
    loopback_ipv4_pool: 10.250.1.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 10.255.1.0/24
    uplink_switches: [ DC1-spine1, DC1-spine2 ]
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    uplink_ipv4_pool: 172.16.1.0/24
    mlag_interfaces: [ Ethernet7, Ethernet8 ]
    mlag_peer_ipv4_pool: 10.251.1.0/24
    mlag_peer_l3_ipv4_pool: 10.252.1.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
  node_groups:
    - group: DC1_RACK1
      bgp_as: 65101
      nodes:
        - name: DC1-leaf1-A
          id: 1
          mgmt_ip: 192.168.0.33/24
          uplink_switch_interfaces: [ Ethernet1, Ethernet2 ]
        - name: DC1-leaf1-B
          id: 2
          mgmt_ip: 192.168.0.34/24
          uplink_switch_interfaces: [ Ethernet1, Ethernet2 ]
    - group: DC1_RACK2
      bgp_as: 65102
      nodes:
        - name: DC1-leaf2-A
          id: 3
          mgmt_ip: 192.168.0.35/24
          uplink_switch_interfaces: [ Ethernet1, Ethernet2 ]
        - name: DC1-leaf2-B
          id: 4
          mgmt_ip: 192.168.0.36/24
          uplink_switch_interfaces: [ Ethernet1, Ethernet2 ]
    # - group: S1_BRDR
    #   bgp_as: 65103
    #   evpn_gateway:
    #     evpn_l2:
    #       enabled: true
    #     evpn_l3:
    #       enabled: true
    #       inter_domain: true
    #   nodes:
    #     - name: s1-brdr1
    #       id: 5
    #       mgmt_ip: 192.168.0.100/24
    #       uplink_switch_interfaces: [ Ethernet7, Ethernet7 ]
    #       evpn_gateway:
    #         remote_peers: 
    #           - hostname: s2-brdr1
    #             bgp_as: 65203
    #             ip_address: 10.250.2.7
    #     - name: s1-brdr2
    #       id: 6
    #       mgmt_ip: 192.168.0.101/24
    #       uplink_switch_interfaces: [ Ethernet8, Ethernet8 ]
    #       evpn_gateway:
    #         remote_peers: 
    #           - hostname: s2-brdr2
    #             bgp_as: 65203
    #             ip_address: 10.250.2.8
